// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001131445_InitialCreateDatabase")]
    partial class InitialCreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Đồ uống",
                            Description = "Nước ngọt, nước suối, trà, cà phê, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Thực phẩm ăn liền",
                            Description = "Cơm, mì, sandwich, burger, bánh mì và đồ ăn nóng"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, khoai tây chiên, bánh quy, kẹo và chocolate"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sữa & sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai và đồ uống từ sữa"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Thực phẩm khô & đóng gói",
                            Description = "Mì gói, ngũ cốc, đồ hộp và thực phẩm đóng gói"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "12 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Võ Văn Tần, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "128 Xô Viết Nghệ Tĩnh, Phường 21, Quận Bình Thạnh, TP. Hồ Chí Minh",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "76 Nguyễn Thị Thập, Phường Tân Phú, Quận 7, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904455667",
                            RewardPoints = 200
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "215 Cộng Hòa, Phường 13, Quận Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Văn E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0935566778",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "93 Quang Trung, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Võ Thị F",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0976677889",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "150 Võ Nguyên Giáp, Phường Thảo Điền, TP. Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Văn G",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0967788990",
                            RewardPoints = 300
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "68 Sư Vạn Hạnh, Phường 12, Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0948899001",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "320 Hà Huy Giáp, Phường Thạnh Lộc, Quận 12, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Văn I",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0929900112",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "84 Phan Xích Long, Phường 2, Quận Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Ngô Thị K",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0911011223",
                            RewardPoints = 180
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893000000001",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Coca-Cola lon 330ml",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893000000002",
                            CategoryId = 1,
                            Price = 7000m,
                            ProductName = "Nước suối Aquafina 500ml",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893000000003",
                            CategoryId = 1,
                            Price = 11000m,
                            ProductName = "Trà xanh Không Độ 455ml",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893000000004",
                            CategoryId = 2,
                            Price = 35000m,
                            ProductName = "Cơm gà sốt tiêu đen",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893000000005",
                            CategoryId = 2,
                            Price = 25000m,
                            ProductName = "Sandwich trứng jambon",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893000000006",
                            CategoryId = 2,
                            Price = 22000m,
                            ProductName = "Bánh mì xúc xích",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893000000007",
                            CategoryId = 3,
                            Price = 10000m,
                            ProductName = "Snack khoai tây Oishi",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893000000008",
                            CategoryId = 3,
                            Price = 18000m,
                            ProductName = "Bánh Oreo 133g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893000000009",
                            CategoryId = 3,
                            Price = 15000m,
                            ProductName = "Chocolate KitKat",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893000000010",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Sữa tươi Vinamilk 180ml",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893000000011",
                            CategoryId = 4,
                            Price = 7000m,
                            ProductName = "Sữa chua Vinamilk",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893000000012",
                            CategoryId = 4,
                            Price = 32000m,
                            ProductName = "Phô mai Con Bò Cười",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893000000013",
                            CategoryId = 5,
                            Price = 4500m,
                            ProductName = "Mì Hảo Hảo tôm chua cay",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893000000014",
                            CategoryId = 5,
                            Price = 8000m,
                            ProductName = "Cháo ăn liền thịt bằm",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893000000015",
                            CategoryId = 5,
                            Price = 22000m,
                            ProductName = "Cá hộp sốt cà",
                            StockQuantity = 35
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
